[package]
name = "code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
thiserror = "1.0.40"

[lib]
name = "code"
# NOTE Declaring the main module path
path = "src/lib/mod.rs"
